/**
 * Decode compact CAPES dataset format generated by Code/build_programas_json.py.
 *
 * Format:
 * - f: ordered field names
 * - d: symbol tables by field (string arrays)
 * - r: rows (arrays of raw values or symbol indexes)
 *
 * @param {{f:string[], d:Record<string, string[]>, r:Array<Array<number|string|null>>}} compact
 * @returns {Array<Record<string, number|string|null>>}
 */
export function decodeCompactDataset(compact) {
  const fields = compact?.f ?? [];
  const dicts = compact?.d ?? {};
  const rows = compact?.r ?? [];

  return rows.map((row) => {
    const out = {};
    for (let i = 0; i < fields.length; i += 1) {
      const field = fields[i];
      const value = row[i];
      const dict = dicts[field];
      out[field] = Array.isArray(dict) && Number.isInteger(value) ? dict[value] : value;
    }
    return out;
  });
}
